import type { Metadata } from "next";
import {Markazi_Text } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const inter = Markazi_Text({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
